### ISSUE TITLE
wrong apt repository in docker-install

### ISSUE THREAD

**Issue by mehranasghari** [devopshobbies/ansible-templates#42]
Hi.
Part04-docker-install, section "apt_repository", line 19 give us wrong repository address. Variable "{{ ansible_architecture }}" leads us to the wrong architecture "x86_64". Correct architecture is "amd64" according to the [docker official site](https://docs.docker.com/engine/install/ubuntu/).

**Comment by mehdi-ra** [comment]
It seems that the problem is fixed. @mehranasghari.
Let me know if a problem exists.
